default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: conecta_trampos_development
  username: postgres
  password: 784512
  host: localhost
  port: 5432

test:
  <<: *default
  database: conecta_trampos_test
  username: postgres
  password: 784512
  host: localhost
  port: 5432


production:
  primary: &primary_production
    <<: *default
    database: conecta_trampos_production
    username: conecta_trampos
    password: <%= ENV["CONECTA_TRAMPOS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: conecta_trampos_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: conecta_trampos_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: conecta_trampos_production_cable
    migrations_paths: db/cable_migrate
