default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  username: postgres
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  database: conecta_trampos_development
  port: 5432

test:
  <<: *default
  host: localhost
  username: postgres
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  database: conecta_trampos_test
  port: 5432

production:
  primary: &primary_production
    <<: *default
    host: <%= ENV.fetch('POSTGRES_HOST', 'conecta_trampos-db') %>
    username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
    password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>
    database: <%= ENV.fetch('POSTGRES_DB', 'conecta_trampos_production') %>
    port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>
  cable:
    <<: *primary_production
    database: conecta_trampos_production_cable # ou o mesmo nome da primary
  cache:
    <<: *primary_production
    database: conecta_trampos_production_cache
  queue:
    <<: *primary_production
    database: conecta_trampos_production_queue
