default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>
  database: <%= ENV.fetch('POSTGRES_DB', 'conecta_trampos_development') %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>

test:
  <<: *default
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>
  database: conecta_trampos_test
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>

production:
  <<: *default
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>  # ← Adicionar default
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>  # ← Adicionar default
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>  # ← Adicionar default
  database: <%= ENV.fetch('POSTGRES_DB', 'conecta_trampos_production') %>  # ← Adicionar default
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>