service: conecta_trampos

# No GHCR, a imagem deve seguir este padrão:
image: maurobiazutti/conecta_trampos

servers:
  web:
    hosts:
      - 192.168.1.5

registry:
  server: ghcr.io
  username: maurobiazutti
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configurações de boot e deploy
boot:
  limit: 30 # Tempo máximo para o container iniciar
  wait: 120 # Esperar até 90 segundos pelo health check passar (60s de start-period + margem)

# Variáveis de Ambiente
env:
  clear:
    PORT: 80
    POSTGRES_HOST: conecta_trampos-db
    POSTGRES_PORT: 5432
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 784512
    POSTGRES_DB: conecta_trampos_production
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: true
    SOLID_QUEUE_IN_PUMA: "true"
  secret:
    - RAILS_MASTER_KEY
    - KAMAL_REGISTRY_PASSWORD
    # - POSTGRES_PASSWORD

# Aliases úteis para gerenciar o app no servidor
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

# Volumes para persistência de arquivos (Active Storage)
volumes:
  - "conecta_trampos_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

# Configuração do Banco de Dados Postgres
accessories:
  db:
    image: postgres:16
    host: 192.168.1.5
    port: "5432:5432"
    env:
      clear:
        POSTGRES_USER: postgres
        POSTGRES_DB: conecta_trampos_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
